# Generated by Django 5.1.3 on 2024-12-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='search_key',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
