# Generated by Django 5.1.3 on 2024-12-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_stock_search_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='search_key',
        ),
    ]
