# Generated by Django 5.1.3 on 2024-12-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_stock_search_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='search_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
