# Generated by Django 5.1.3 on 2024-12-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_reviewsratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsratings',
            old_name='Product',
            new_name='product',
        ),
    ]
