# Generated by Django 5.1.3 on 2024-12-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_coupon_bulkpurchaseoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkpurchaseoffer',
            old_name='discount',
            new_name='fixed_discount',
        ),
        migrations.AddField(
            model_name='bulkpurchaseoffer',
            name='is_fixed',
            field=models.BooleanField(default=True),
        ),
    ]
