# Generated by Django 5.1.3 on 2024-12-30 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_discount_bulkpurchaseoffer_fixed_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpurchaseoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_offer_product', to='store.product'),
        ),
    ]
