# Generated by Django 5.1.3 on 2024-12-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0010_alter_stock_variation_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stock'),
        ),
    ]
