# Generated by Django 5.1.3 on 2024-12-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('min_amount', models.IntegerField()),
                ('discount', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
