# Generated by Django 5.1.3 on 2024-12-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_cartitem_item_price_cartitem_d_item_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['id']},
        ),
    ]
