# Generated by Django 5.1.3 on 2025-01-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
