# Generated by Django 5.1.3 on 2024-12-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraddresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
