# Generated by Django 5.1.3 on 2024-12-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraddresses_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddresses',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
