# Generated by Django 5.1.3 on 2024-12-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_name_useraddresses_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
