# Generated by Django 5.1.3 on 2024-12-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='userprofile/default.jpg', null=True, upload_to='userprofile'),
        ),
    ]
