# Generated by Django 5.1.3 on 2025-01-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment_failure_reason_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Pay Now', 'Pay Now')], default='Cash on Delivery', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confiremd', 'Confiremd'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return', 'Return')], default='New', max_length=10),
        ),
    ]
