# Generated by Django 5.1.3 on 2025-01-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_mode_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('Cash on Delivery', 'cash_on_delivery'), ('Pay Now', 'pay_ow')], default='cash_on_delivery', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confiremd', 'confiremd'), ('Shipped', 'shipped'), ('Delivered', 'delivered'), ('Cancelled', 'cancelled'), ('Return', 'return')], default='confirmed', max_length=10),
        ),
    ]
