# Generated by Django 5.1.3 on 2025-01-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_mode_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
