# Generated by Django 5.1.3 on 2025-01-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_payment_payment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Confiremd', 'confiremd'), ('Shipped', 'shipped'), ('Delivered', 'delivered'), ('Cancelled', 'cancelled'), ('Return', 'return')], default='confirmed', max_length=10),
        ),
    ]
