# Generated by Django 5.1.3 on 2025-01-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_couponhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponhistory',
            name='is_current_seesion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couponhistory',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='couponhistory',
            name='availed_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
