# Generated by Django 5.1.3 on 2025-01-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_couponhistory_is_current_seesion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponhistory',
            old_name='is_current_seesion',
            new_name='is_current_session',
        ),
    ]
