# Generated by Django 5.1.3 on 2025-01-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rename_is_current_seesion_couponhistory_is_current_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponhistory',
            name='is_current_session',
        ),
    ]
