# Generated by Django 5.1.3 on 2025-01-08 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_couponhistory_is_current_session'),
        ('store', '0016_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='store.coupon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='net_order_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
