# Generated by Django 5.1.3 on 2025-01-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'confirmed'), ('Shipped', 'shipped'), ('Delivered', 'delivered'), ('Cancelled', 'cancelled'), ('Return', 'return')], default='confirmed', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'confirmed'), ('Shipped', 'shipped'), ('Delivered', 'delivered'), ('Cancelled', 'cancelled'), ('Return', 'return')], default='confirmed', max_length=50),
        ),
    ]
