# Generated by Django 5.1.3 on 2025-01-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_remove_cartitem_variations'),
        ('orders', '0018_alter_order_status_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponhistory',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='carts.cart'),
            preserve_default=False,
        ),
    ]
