# Generated by Django 5.1.3 on 2025-01-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_couponhistory_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponhistory',
            name='cart',
        ),
        migrations.AddField(
            model_name='couponhistory',
            name='coupon_user_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
