# Generated by Django 5.1.3 on 2025-01-11 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_couponhistory_cart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponhistory',
            name='coupon_user_id',
        ),
        migrations.AddField(
            model_name='couponhistory',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_coupon', to=settings.AUTH_USER_MODEL),
        ),
    ]
