# Generated by Django 5.1.3 on 2025-01-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_remove_cartitem_variations'),
        ('orders', '0023_remove_couponhistory_coupon_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponhistory',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_coupon', to='carts.cart'),
        ),
    ]
