# Generated by Django 5.1.3 on 2025-01-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_couponhistory_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'confirmed'), ('Shipped', 'shipped'), ('Delivered', 'delivered'), ('Cancelled', 'cancelled'), ('Return', 'return')], default='new', max_length=50),
        ),
    ]
