# Generated by Django 5.1.3 on 2025-01-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_orderproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
    ]
