# Generated by Django 5.1.3 on 2025-01-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_orderproduct_status_wallet_wallettransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='grand_order_total',
        ),
    ]
