# Generated by Django 5.1.3 on 2025-01-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_rename_order_total_order_grand_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grand_order_total',
        ),
    ]
