# Generated by Django 5.1.3 on 2025-01-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_sub_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_order_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_ammount',
            field=models.FloatField(default=0.0),
        ),
    ]
