# Generated by Django 5.1.3 on 2025-01-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_current_order_total_order_refunded_ammount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refunded_ammount',
            new_name='refunded_amount',
        ),
    ]
