# Generated by Django 5.1.3 on 2025-01-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_rename_refunded_ammount_order_refunded_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_amount',
            field=models.FloatField(),
        ),
    ]
