# Generated by Django 5.1.3 on 2025-01-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_wallettransaction_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_balance',
            field=models.FloatField(),
        ),
    ]
