# Generated by Django 5.1.3 on 2025-01-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_wallet_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged or Defective Product'), ('WRONG_PRODUCT', 'Wrong Product Delivered'), ('SIZE_ISSUE', 'Size or Fit Issues'), ('NOT_AS_DESCRIBED', 'Product Not as Described'), ('MISSING_ITEMS', 'Missing Items'), ('QUALITY_ISSUE', 'Quality Issues'), ('PERFORMANCE_ISSUE', 'Performance Issues'), ('EXPIRED_PRODUCT', 'Expired Product'), ('CHANGE_OF_MIND', 'Change of Mind'), ('BETTER_PRICE', 'Better Price Available'), ('TAMPERED_PACKAGE', 'Package Tampered')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('refund_ammount', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_return', to='orders.orderproduct')),
            ],
        ),
    ]
