# Generated by Django 5.1.3 on 2025-01-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_return_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='return_product',
            new_name='ReturnProduct',
        ),
    ]
