# Generated by Django 5.1.3 on 2025-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_alter_returnproduct_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproduct',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('closed', 'Closed')], max_length=50),
        ),
    ]
