# Generated by Django 5.1.3 on 2025-01-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_returnproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproduct',
            name='refund_ammount',
            field=models.FloatField(default=0.0),
        ),
    ]
