# Generated by Django 5.1.3 on 2025-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_returnproduct_refund_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='returnproduct',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('refund_completed', 'Refund Completed')], max_length=50),
        ),
    ]
