# Generated by Django 5.1.3 on 2025-02-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_alter_wallet_wallet_balance'),
        ('store', '0017_alter_variation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ordered', to='store.product'),
        ),
    ]
